"""Catalog repository: typed queries and mutations over the SQLite catalog.

All catalog access goes through these module-level functions so higher layers
never write raw SQL. Rows are mapped to the dataclasses in ``models.py``.
"""

from __future__ import annotations

import sqlite3

from .models import (
    Album,
    ArchiveState,
    Asset,
    AssetFile,
    DeletionMark,
    FileLocation,
    ImportSession,
    PhoneItem,
)


def repository_last_row_id(cursor: sqlite3.Cursor) -> int:
    """Return the primary key generated by an INSERT.

    cursor: the cursor returned by the INSERT statement.
    Returns the generated integer id. SQLite always sets ``lastrowid`` after a
    successful single-row INSERT into a table with a rowid, so a missing value
    indicates a programming error.
    """
    row_id = cursor.lastrowid
    if row_id is None:
        raise RuntimeError("INSERT did not produce a row id")
    return row_id


def repository_row_to_asset(row: sqlite3.Row) -> Asset:
    """Map a database row to an ``Asset`` dataclass.

    row: a sqlite3 row from the ``assets`` table.
    Returns the corresponding ``Asset``.
    """
    return Asset(
        asset_id=row["id"],
        sha256=row["sha256"],
        size=row["size"],
        original_name=row["original_name"],
        media_type=row["media_type"],
        captured_at=row["captured_at"],
        imported_at=row["imported_at"],
        verified_at=row["verified_at"],
        first_seen_on_phone_at=row["first_seen_on_phone_at"],
        last_seen_on_phone_at=row["last_seen_on_phone_at"],
        present_on_phone=bool(row["present_on_phone"]),
        archive_state=ArchiveState(row["archive_state"]),
        phone_asset_id=row["phone_asset_id"],
        phone_path=row["phone_path"],
        phone_size=row["phone_size"],
        phone_modified_at=row["phone_modified_at"],
    )


def repository_insert_asset(connection: sqlite3.Connection, asset: Asset) -> int:
    """Insert a new asset row and return its generated id.

    connection: an open catalog connection.
    asset: the asset to insert (its ``asset_id`` is ignored).
    Returns the new integer primary key.
    """
    cursor = connection.execute(
        """
        INSERT INTO assets(
            sha256, size, original_name, media_type, captured_at, imported_at,
            verified_at, first_seen_on_phone_at, last_seen_on_phone_at,
            present_on_phone, archive_state, phone_asset_id, phone_path,
            phone_size, phone_modified_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            asset.sha256,
            asset.size,
            asset.original_name,
            asset.media_type,
            asset.captured_at,
            asset.imported_at,
            asset.verified_at,
            asset.first_seen_on_phone_at,
            asset.last_seen_on_phone_at,
            int(asset.present_on_phone),
            asset.archive_state.value,
            asset.phone_asset_id,
            asset.phone_path,
            asset.phone_size,
            asset.phone_modified_at,
        ),
    )
    return repository_last_row_id(cursor)


def repository_get_asset(connection: sqlite3.Connection, asset_id: int) -> Asset | None:
    """Return the asset with the given identifier, or None.

    connection: an open catalog connection.
    asset_id: the catalog identifier to look up.
    Returns the matching ``Asset`` or None when absent.
    """
    row = connection.execute("SELECT * FROM assets WHERE id = ?", (asset_id,)).fetchone()
    result = repository_row_to_asset(row) if row is not None else None
    return result


def repository_get_asset_by_hash(connection: sqlite3.Connection, sha256: str) -> Asset | None:
    """Return the asset with the given content hash, or None.

    connection: an open catalog connection.
    sha256: the content hash to look up.
    Returns the matching ``Asset`` or None when absent.
    """
    row = connection.execute("SELECT * FROM assets WHERE sha256 = ?", (sha256,)).fetchone()
    result = repository_row_to_asset(row) if row is not None else None
    return result


def repository_find_by_phone_identity(
    connection: sqlite3.Connection,
    phone_asset_id: str | None,
    phone_path: str | None,
    phone_size: int | None,
    device_udid: str | None = None,
    phone_modified_at: str | None = None,
) -> Asset | None:
    """Find an asset by phone identity for the fast-skip import pass.

    connection: an open catalog connection.
    phone_asset_id: the phone asset id, which must also match when available.
    phone_path: exact source path on the identified device.
    phone_size: observed byte size.
    device_udid: required device provenance; unknown devices cannot fast-skip.
    phone_modified_at: required nonempty observed modification metadata.
    Returns one unambiguous byte-verified identity, or None for legacy/unknown data.
    """
    if not device_udid or not phone_path or phone_size is None or not phone_modified_at:
        return None
    rows = connection.execute(
        """
        SELECT assets.* FROM assets JOIN source_identities AS source
          ON source.asset_id = assets.id
        WHERE source.device_udid = ? AND source.phone_path = ?
          AND source.phone_size = ? AND source.phone_modified_at = ?
          AND source.phone_asset_id IS ?
        """,
        (device_udid, phone_path, phone_size, phone_modified_at, phone_asset_id),
    ).fetchall()
    return repository_row_to_asset(rows[0]) if len(rows) == 1 else None


def repository_record_source(
    connection: sqlite3.Connection,
    asset_id: int,
    device_udid: str | None,
    item: PhoneItem,
) -> None:
    """Record a byte-verified source identity without publishing scan presence."""
    if not device_udid:
        return
    connection.execute(
        """
        INSERT INTO source_identities(
            device_udid, phone_path, asset_id, phone_asset_id, phone_size, phone_modified_at
        ) VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT(device_udid, phone_path, asset_id) DO UPDATE SET
            phone_asset_id = excluded.phone_asset_id,
            phone_size = excluded.phone_size,
            phone_modified_at = excluded.phone_modified_at
        """,
        (device_udid, item.phone_path, asset_id, item.phone_asset_id, item.size, item.modified_at),
    )


def repository_publish_presence(
    connection: sqlite3.Connection,
    device_udid: str | None,
    seen: list[tuple[str, int]],
    scanned_at: str,
) -> None:
    """Atomically publish one complete device inventory, leaving other devices intact."""
    if not device_udid:
        return
    connection.execute(
        "UPDATE source_identities SET present = 0 WHERE device_udid = ?", (device_udid,)
    )
    connection.executemany(
        """UPDATE source_identities SET present = 1, last_seen_at = ?
           WHERE device_udid = ? AND phone_path = ? AND asset_id = ?""",
        [(scanned_at, device_udid, phone_path, asset_id) for phone_path, asset_id in seen],
    )
    connection.execute(
        """UPDATE assets SET present_on_phone = EXISTS(
             SELECT 1 FROM source_identities WHERE asset_id = assets.id AND present = 1)
           WHERE id IN (SELECT asset_id FROM source_identities WHERE device_udid = ?)""",
        (device_udid,),
    )
    for asset_id in {asset_id for _, asset_id in seen}:
        repository_mark_present(connection, asset_id, scanned_at)


def repository_insert_asset_file(connection: sqlite3.Connection, asset_file: AssetFile) -> int:
    """Insert a stored-file row for an asset and return its id.

    connection: an open catalog connection.
    asset_file: the on-disk copy descriptor to insert.
    Returns the new integer primary key.
    """
    cursor = connection.execute(
        """
        INSERT INTO asset_files(asset_id, path, album_id, link_mode, location)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            asset_file.asset_id,
            asset_file.path,
            asset_file.album_id,
            asset_file.link_mode,
            asset_file.location.value,
        ),
    )
    return repository_last_row_id(cursor)


def repository_list_asset_files(connection: sqlite3.Connection, asset_id: int) -> list[AssetFile]:
    """List all on-disk copies recorded for an asset.

    connection: an open catalog connection.
    asset_id: the asset whose files to list.
    Returns a list of ``AssetFile`` rows.
    """
    rows = connection.execute(
        "SELECT * FROM asset_files WHERE asset_id = ?", (asset_id,)
    ).fetchall()
    return [
        AssetFile(
            file_id=row["id"],
            asset_id=row["asset_id"],
            path=row["path"],
            album_id=row["album_id"],
            link_mode=row["link_mode"],
            location=FileLocation(row["location"]),
        )
        for row in rows
    ]


def repository_all_asset_files(connection: sqlite3.Connection) -> list[AssetFile]:
    """List every stored file across all assets (used by verification).

    connection: an open catalog connection.
    Returns a list of all ``AssetFile`` rows.
    """
    rows = connection.execute("SELECT * FROM asset_files").fetchall()
    return [
        AssetFile(
            file_id=row["id"],
            asset_id=row["asset_id"],
            path=row["path"],
            album_id=row["album_id"],
            link_mode=row["link_mode"],
            location=FileLocation(row["location"]),
        )
        for row in rows
    ]


def repository_update_asset_file_path(
    connection: sqlite3.Connection, file_id: int, new_path: str, location: FileLocation
) -> None:
    """Update the path and location of a stored file (used by move/recycle).

    connection: an open catalog connection.
    file_id: the ``asset_files`` row to update.
    new_path: the new on-disk path.
    location: the new location class.
    Returns None.
    """
    connection.execute(
        "UPDATE asset_files SET path = ?, location = ? WHERE id = ?",
        (new_path, location.value, file_id),
    )


def repository_upsert_album(connection: sqlite3.Connection, album: Album) -> int:
    """Insert or fetch an album by safe name and return its id.

    connection: an open catalog connection.
    album: the album to ensure exists.
    Returns the album's integer primary key.
    """
    row = connection.execute(
        "SELECT id FROM albums WHERE safe_name = ?", (album.safe_name,)
    ).fetchone()
    if row is not None:
        album_id = int(row["id"])
    else:
        cursor = connection.execute(
            "INSERT INTO albums(phone_album_id, name, safe_name, kind) VALUES (?, ?, ?, ?)",
            (album.phone_album_id, album.name, album.safe_name, album.kind),
        )
        album_id = repository_last_row_id(cursor)
    return album_id


def repository_link_asset_album(
    connection: sqlite3.Connection, asset_id: int, album_id: int
) -> None:
    """Record membership of an asset in an album (idempotent).

    connection: an open catalog connection.
    asset_id: the asset side of the membership.
    album_id: the album side of the membership.
    Returns None.
    """
    connection.execute(
        "INSERT OR IGNORE INTO asset_albums(asset_id, album_id) VALUES (?, ?)",
        (asset_id, album_id),
    )


def repository_page_clause(limit: int | None, offset: int = 0) -> tuple[str, list[int]]:
    """Build validated SQLite pagination; None preserves existing unbounded listings."""
    if type(offset) is not int or offset < 0:
        raise ValueError("listing offset must be a non-negative integer")
    if limit is not None and (type(limit) is not int or limit < 0):
        raise ValueError("listing limit must be a non-negative integer or None")
    if limit is not None:
        return " LIMIT ? OFFSET ?", [limit, offset]
    if offset:
        return " LIMIT -1 OFFSET ?", [offset]
    return "", []


def repository_list_albums(connection: sqlite3.Connection) -> list[Album]:
    """List all albums known to the catalog.

    connection: an open catalog connection.
    Returns a list of ``Album`` rows.
    """
    rows = connection.execute("SELECT * FROM albums ORDER BY safe_name").fetchall()
    return [
        Album(
            album_id=row["id"],
            phone_album_id=row["phone_album_id"],
            name=row["name"],
            safe_name=row["safe_name"],
            kind=row["kind"],
        )
        for row in rows
    ]


def repository_mark_all_absent(connection: sqlite3.Connection) -> None:
    """Reset the present-on-phone flag for all assets before a fresh scan.

    connection: an open catalog connection.
    Returns None.
    """
    connection.execute("UPDATE assets SET present_on_phone = 0")


def repository_mark_present(connection: sqlite3.Connection, asset_id: int, seen_at: str) -> None:
    """Mark an asset as present on the phone and update its last-seen time.

    connection: an open catalog connection.
    asset_id: the asset seen during the scan.
    seen_at: ISO timestamp of the scan.
    Returns None.
    """
    connection.execute(
        """
        UPDATE assets
        SET present_on_phone = 1,
            last_seen_on_phone_at = ?,
            first_seen_on_phone_at = COALESCE(first_seen_on_phone_at, ?)
        WHERE id = ?
        """,
        (seen_at, seen_at, asset_id),
    )


def repository_list_deleted_from_phone(
    connection: sqlite3.Connection, device_udid: str | None = None
) -> list[Asset]:
    """List active assets that were not seen in the latest phone scan.

    connection: an open catalog connection.
    Returns active-archive assets with ``present_on_phone`` false.
    """
    if device_udid is None:
        rows = connection.execute(
            "SELECT * FROM assets WHERE present_on_phone = 0 AND archive_state = 'active'"
        ).fetchall()
    else:
        rows = connection.execute(
            """SELECT * FROM assets WHERE archive_state = 'active'
               AND id IN (SELECT asset_id FROM source_identities WHERE device_udid = ?)
               AND id NOT IN (SELECT asset_id FROM source_identities
                              WHERE device_udid = ? AND present = 1)""",
            (device_udid, device_udid),
        ).fetchall()
    return [repository_row_to_asset(row) for row in rows]


def repository_set_archive_state(
    connection: sqlite3.Connection, asset_id: int, state: ArchiveState
) -> None:
    """Update the archive state of an asset (active/deleted).

    connection: an open catalog connection.
    asset_id: the asset to update.
    state: the new archive state.
    Returns None.
    """
    connection.execute("UPDATE assets SET archive_state = ? WHERE id = ?", (state.value, asset_id))


def repository_set_verified_at(
    connection: sqlite3.Connection, asset_id: int, verified_at: str
) -> None:
    """Record the last successful verification time for an asset.

    connection: an open catalog connection.
    asset_id: the asset that was verified.
    verified_at: ISO timestamp of the verification.
    Returns None.
    """
    connection.execute("UPDATE assets SET verified_at = ? WHERE id = ?", (verified_at, asset_id))


def repository_delete_asset(connection: sqlite3.Connection, asset_id: int) -> None:
    """Remove an asset and its dependent rows from the catalog.

    connection: an open catalog connection.
    asset_id: the asset to delete (cascades to files/albums/memberships).
    Returns None.
    """
    connection.execute("DELETE FROM assets WHERE id = ?", (asset_id,))


def repository_create_import_session(connection: sqlite3.Connection, session: ImportSession) -> int:
    """Create an import-session row and return its id.

    connection: an open catalog connection.
    session: the session metadata to persist.
    Returns the new integer primary key.
    """
    cursor = connection.execute(
        """
        INSERT INTO import_sessions(
            device_udid, started_at, finished_at, added_count, skipped_count, error_count
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            session.device_udid,
            session.started_at,
            session.finished_at,
            session.added_count,
            session.skipped_count,
            session.error_count,
        ),
    )
    return repository_last_row_id(cursor)


def repository_finish_import_session(
    connection: sqlite3.Connection, session: ImportSession
) -> None:
    """Update an import session with its final counts and finish time.

    connection: an open catalog connection.
    session: the session to update (must carry ``session_id``).
    Returns None.
    """
    connection.execute(
        """
        UPDATE import_sessions
        SET finished_at = ?, added_count = ?, skipped_count = ?, error_count = ?
        WHERE id = ?
        """,
        (
            session.finished_at,
            session.added_count,
            session.skipped_count,
            session.error_count,
            session.session_id,
        ),
    )


def repository_add_deletion_mark(connection: sqlite3.Connection, mark: DeletionMark) -> int:
    """Stage a mark-for-delete row and return its id.

    connection: an open catalog connection.
    mark: the mark to stage (not yet committed).
    Returns the new integer primary key.
    """
    cursor = connection.execute(
        """
        INSERT INTO deletion_marks(target_type, target_id, marked_at, reason, committed_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        (mark.target_type, mark.target_id, mark.marked_at, mark.reason, mark.committed_at),
    )
    return repository_last_row_id(cursor)


def repository_list_pending_marks(connection: sqlite3.Connection) -> list[DeletionMark]:
    """List deletion marks that have not yet been committed.

    connection: an open catalog connection.
    Returns pending ``DeletionMark`` rows.
    """
    rows = connection.execute("SELECT * FROM deletion_marks WHERE committed_at IS NULL").fetchall()
    return [
        DeletionMark(
            mark_id=row["id"],
            target_type=row["target_type"],
            target_id=row["target_id"],
            marked_at=row["marked_at"],
            reason=row["reason"],
            committed_at=row["committed_at"],
        )
        for row in rows
    ]


def repository_commit_mark(connection: sqlite3.Connection, mark_id: int, committed_at: str) -> None:
    """Mark a staged deletion mark as committed.

    connection: an open catalog connection.
    mark_id: the mark to finalize.
    committed_at: ISO timestamp of the commit.
    Returns None.
    """
    connection.execute(
        "UPDATE deletion_marks SET committed_at = ? WHERE id = ?", (committed_at, mark_id)
    )
